### ISSUE TITLE
Tooltip overflow checking not working as expected

### ISSUE THREAD

**Issue by flopes89** [julmot/jmTooltip#1]
When the tooltip content is too long (in any direction), the overflow check will not always make it so that the tooltip is moved accordingly - The main case being when the element that contains the text that shows the tooltip is not as wide or high as the page.

Because https://github.com/julmot/jmTooltip/blob/master/src/jquery.jmTooltip.js#L276 only checks the body-width, this can result in the following in the tooltip being hidden behind the containing element;

![tooltip-1](https://cloud.githubusercontent.com/assets/1453127/7198648/9b755d8c-e4ee-11e4-86a4-b86b361b39d6.png)
![tooltip-2](https://cloud.githubusercontent.com/assets/1453127/7198647/9b7495be-e4ee-11e4-9128-b98e165e5b6d.png)

**Comment by julmot** [comment]
@flopes89 You should make sure that the tooltip has a `z-index` higher than the parent element. Also make sure the parent is not `overflow:hidden`. It seems that your tooltip is wrapped within a element that doesn't allow the overlap.
However, I'll implement a option to provide a element reference for the calculation in the next days.

**Comment by flopes89** [comment]
Alright, so the z-index was fine, but I changed the containing `div.container` element to not have `overlfow:hidden`, which it did at first.

Now, without any `overflow`-setting, it seems to work fine.

**Comment by julmot** [comment]
Regardless of the `overflow`-fix the reference object was implemented in 3.1.0!
